plugins {
    id 'java'
}

group = 'kuit.com'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation("org.mockito:mockito-all:1.10.19")
}

test {
    useJUnitPlatform()
}